name: 'Terraform CI/CD'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'
  ECR_REPOSITORY: tm

jobs:
  Slack_Notifications:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#Joel-DevOps'
          message: Starting CI/CD Pipeline...

  terraform_static_analysis:
    name: 'Terraform Static Analysis'
    runs-on: ubuntu-latest
    needs: Slack_Notifications
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: tf-mods-version
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - run: terraform init
      - run: terraform validate
      - run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version
      - run: tflint

  terraform_plan_test:
    name: 'Terraform Plan for Test'
    runs-on: ubuntu-latest
    needs: terraform_static_analysis
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - run: |
          terraform init
          terraform plan -out=plan-test
          terraform show -no-color plan-test > plan-test.txt
        working-directory: tf-mods-version
      - uses: actions/upload-artifact@v4
        with:
          name: plan-test
          path: tf-mods-version/plan-test.txt

  build_and_push:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    needs: terraform_plan_test
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

  trivy_scan:
    name: 'Trivy Image Scan for Vulnerabilities'
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: docker pull $ECR_REGISTRY/2048:$IMAGE_TAG
      - uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: public.ecr.aws/c7u5x4r5/tm:latest
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH
          output: trivy-report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Trivy Scan Report
          path: trivy-report.txt
      - run: cat trivy-report.txt

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: trivy_scan
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation == 'yes'
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - run: |
          terraform init
          terraform apply -auto-approve
        working-directory: tf-mods-version

  Slack_Notifications_Complete:
    name: Slack Notifications (Complete)
    runs-on: ubuntu-latest
    needs: terraform_apply
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#Joel-DevOps'
          message: 'CI/CD Pipeline Completed'
        if: always()
 
     
      # - name: Update ECS Service to use the latest image
      #   run: |
      #     aws ecs update-service \
      #       --cluster ${{ env.ECS_CLUSTER }} \
      #       --service ${{ env.ECS_SERVICE }} \
      #       --force-new-deployment \
      #       --output json

      # - name: Fill in the new image ID in the Amazon ECS task definition
      #   id: task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: task-definition.json
      #     container-name: tmc
      #     image: ${{ steps.build-image.outputs.image }}

      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     service: ${{ env.ECS_SERVICE }}
      #     cluster: ${{ env.ECS_CLUSTER }}
      #     wait-for-service-stability: true



      
